name: GigaChat
version: '${project.version}'
main: com.SS1GGzxc.GigaMain.Main
api-version: '1.16'
load: STARTUP
commands:
  Ask:
    description: "Ask GigaChat."
    usage: "/ask <question>"

  SetKey:
    description: "Set authorization key for GigaChat."
    usage: "/setkey <key>"

  SetLanguage:
    description: "Set GigaChat reply language."
    usage: "/setlanguage <en/ru>"